name: Nuitka Packaging

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install imageio

      - name: Install Nuitka
        run: pip install nuitka

      - name: Build with Nuitka (Windows)
        run: |
          nuitka --onefile --windows-icon-from-ico=./assets/icon.png --output-dir=out_windows --output-filename=pubmedsoso.exe --assume-yes-for-downloads main.py

      - name: Check output directory
        run: dir out_windows

      - name: Upload build artifacts (Windows)
        uses: actions/upload-artifact@v4
        with:
          name: nuitka-build-windows
          path: out_windows/pubmedsoso.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install imageio

      - name: Install Nuitka
        run: pip install nuitka

      - name: Build with Nuitka (macOS)
        run: |
          nuitka --onefile --macos-create-app-bundle --macos-app-icon=./assets/icon.png --output-dir=out_macos --output-filename=pubmedsoso.darwin.bin --assume-yes-for-downloads main.py

      - name: Check output directory
        run: ls out_macos

      - name: Upload build artifacts (macOS)
        uses: actions/upload-artifact@v4
        with:
          name: nuitka-build-macos
          path: out_macos/pubmedsoso.darwin.bin

  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Nuitka
        run: pip install nuitka

      - name: Build with Nuitka (Linux)
        run: |
          nuitka --onefile --output-dir=out_linux --output-filename=pubmedsoso.linux.bin --assume-yes-for-downloads main.py

      - name: Check output directory
        run: ls out_linux

      - name: Upload build artifacts (Linux)
        uses: actions/upload-artifact@v4
        with:
          name: nuitka-build-linux
          path: out_linux/pubmedsoso.linux.bin